/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Kalkulator;

import javax.swing.ImageIcon;

/**
 *
 * @author USER
 */
public class MultiCal_Home extends javax.swing.JFrame {

    /**
     * Creates new form MultiCal_MultifunctionalCalculator
     */
    public MultiCal_Home() {
        initComponents();
        this.setLocationRelativeTo(this);
        this.setTitle("MultiCal - Multifunctional Calculator");
        ImageIcon icon = new ImageIcon("src/UAS_1955201016_MULTICAL/calculator logo.png");
        setIconImage(icon.getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jB_basic = new javax.swing.JButton();
        jB_2x2 = new javax.swing.JButton();
        jB_3x3 = new javax.swing.JButton();
        jB_convert = new javax.swing.JButton();
        jB_cancel = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Kalkulator/calculator logo.png"))); // NOI18N
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabel1.setBackground(new java.awt.Color(153, 153, 255));
        jLabel1.setFont(new java.awt.Font("Tekton Pro", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 255));
        jLabel1.setText("WELCOME TO MULTICAL!");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 204, 204));
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 550, -1, -1));

        jLabel3.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 255));
        jLabel3.setText("What would you choose?");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, 290, -1));

        jB_basic.setBackground(new java.awt.Color(101, 134, 177));
        jB_basic.setFont(new java.awt.Font("Tekton Pro", 0, 24)); // NOI18N
        jB_basic.setText("Basic Calculator");
        jB_basic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_basicActionPerformed(evt);
            }
        });
        getContentPane().add(jB_basic, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 180, 378, 57));

        jB_2x2.setBackground(new java.awt.Color(101, 134, 177));
        jB_2x2.setFont(new java.awt.Font("Tekton Pro", 0, 24)); // NOI18N
        jB_2x2.setText("2x2 Matrix Calculator");
        jB_2x2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_2x2ActionPerformed(evt);
            }
        });
        getContentPane().add(jB_2x2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 250, 378, 57));

        jB_3x3.setBackground(new java.awt.Color(101, 134, 177));
        jB_3x3.setFont(new java.awt.Font("Tekton Pro", 0, 24)); // NOI18N
        jB_3x3.setText("3x3 Matrix Calculator");
        jB_3x3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_3x3ActionPerformed(evt);
            }
        });
        getContentPane().add(jB_3x3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 330, 378, 57));

        jB_convert.setBackground(new java.awt.Color(101, 134, 177));
        jB_convert.setFont(new java.awt.Font("Tekton Pro", 0, 24)); // NOI18N
        jB_convert.setText("Number System Converter");
        jB_convert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_convertActionPerformed(evt);
            }
        });
        getContentPane().add(jB_convert, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 400, 378, 57));

        jB_cancel.setBackground(new java.awt.Color(53, 80, 177));
        jB_cancel.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jB_cancel.setText("CANCEL");
        jB_cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_cancelActionPerformed(evt);
            }
        });
        getContentPane().add(jB_cancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 490, 90, 40));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 255));
        jLabel2.setText("-- MULTIFUNCTIONAL CALCULATOR --");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 60, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jB_basicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_basicActionPerformed
        new MultiCal_BasicCalculator().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jB_basicActionPerformed

    private void jB_2x2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_2x2ActionPerformed
        new MultiCal_2x2MatrixCalculator().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jB_2x2ActionPerformed

    private void jB_3x3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_3x3ActionPerformed
        new MultiCal_3x3MatrixCalculator().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jB_3x3ActionPerformed

    private void jB_convertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_convertActionPerformed
        new MultiCal_NumberSystemConverter().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jB_convertActionPerformed

    private void jB_cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_cancelActionPerformed
        dispose();
    }//GEN-LAST:event_jB_cancelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MultiCal_Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MultiCal_Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MultiCal_Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MultiCal_Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MultiCal_Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jB_2x2;
    private javax.swing.JButton jB_3x3;
    private javax.swing.JButton jB_basic;
    private javax.swing.JButton jB_cancel;
    private javax.swing.JButton jB_convert;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    // End of variables declaration//GEN-END:variables
}
