/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Kalkulator;

import javax.swing.ImageIcon;

/**
 *
 * @author USER
 */
public class MultiCal_2x2MatrixCalculator extends javax.swing.JFrame {

    /**
     * Creates new form Multical_2x2MatrixCalculator
     */
    public MultiCal_2x2MatrixCalculator() {
        initComponents();
        this.setTitle("MultiCal - 2x2 Matrix Calculator");
        this.setLocationRelativeTo(this);
        ImageIcon icon = new ImageIcon("src/UAS_1955201016_MULTICAL/calculator logo.png");
        setIconImage(icon.getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bG_matrix2x2 = new javax.swing.ButtonGroup();
        C12 = new javax.swing.JLabel();
        C21 = new javax.swing.JLabel();
        C11 = new javax.swing.JLabel();
        C22 = new javax.swing.JLabel();
        singleres = new javax.swing.JLabel();
        kurung = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jB_calculate = new javax.swing.JButton();
        jB_clear = new javax.swing.JButton();
        subtract = new javax.swing.JRadioButton();
        multiply = new javax.swing.JRadioButton();
        determinan = new javax.swing.JRadioButton();
        transpose = new javax.swing.JRadioButton();
        sum = new javax.swing.JRadioButton();
        matres = new javax.swing.JLabel();
        matB = new javax.swing.JLabel();
        B11 = new javax.swing.JTextField();
        B12 = new javax.swing.JTextField();
        B22 = new javax.swing.JTextField();
        B21 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        matA = new javax.swing.JLabel();
        A12 = new javax.swing.JTextField();
        A11 = new javax.swing.JTextField();
        A22 = new javax.swing.JTextField();
        A21 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jB_back = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        C12.setFont(new java.awt.Font("Cambria Math", 0, 24)); // NOI18N
        C12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        C12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 153, 255)));
        getContentPane().add(C12, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 350, 50, 40));

        C21.setFont(new java.awt.Font("Cambria Math", 0, 24)); // NOI18N
        C21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        C21.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 153, 255)));
        getContentPane().add(C21, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 410, 50, 40));

        C11.setFont(new java.awt.Font("Cambria Math", 0, 24)); // NOI18N
        C11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        C11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 153, 255)));
        getContentPane().add(C11, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 350, 50, 40));

        C22.setFont(new java.awt.Font("Cambria Math", 0, 24)); // NOI18N
        C22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        C22.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 153, 255)));
        getContentPane().add(C22, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 410, 50, 40));

        singleres.setFont(new java.awt.Font("Cambria Math", 0, 24)); // NOI18N
        singleres.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(singleres, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 350, 120, 100));

        kurung.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Kalkulator/kurung siku.png"))); // NOI18N
        getContentPane().add(kurung, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, -1, 140));

        jLabel17.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Which One?");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 300, 150, 40));

        jB_calculate.setBackground(new java.awt.Color(101, 134, 177));
        jB_calculate.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jB_calculate.setText("CALCULATE");
        jB_calculate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_calculateActionPerformed(evt);
            }
        });
        getContentPane().add(jB_calculate, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 450, 120, 40));

        jB_clear.setBackground(new java.awt.Color(101, 134, 177));
        jB_clear.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jB_clear.setText("CLEAR");
        jB_clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_clearActionPerformed(evt);
            }
        });
        getContentPane().add(jB_clear, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 450, 80, 40));

        bG_matrix2x2.add(subtract);
        subtract.setFont(new java.awt.Font("Tekton Pro", 0, 14)); // NOI18N
        subtract.setText("SUBTRACT");
        subtract.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subtractActionPerformed(evt);
            }
        });
        getContentPane().add(subtract, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 380, 90, 23));

        bG_matrix2x2.add(multiply);
        multiply.setFont(new java.awt.Font("Tekton Pro", 0, 14)); // NOI18N
        multiply.setText("MULTIPLY");
        multiply.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                multiplyActionPerformed(evt);
            }
        });
        getContentPane().add(multiply, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 410, 90, 23));

        bG_matrix2x2.add(determinan);
        determinan.setFont(new java.awt.Font("Tekton Pro", 0, 14)); // NOI18N
        determinan.setText("DETERMINAN");
        determinan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                determinanActionPerformed(evt);
            }
        });
        getContentPane().add(determinan, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 350, 110, -1));

        bG_matrix2x2.add(transpose);
        transpose.setFont(new java.awt.Font("Tekton Pro", 0, 14)); // NOI18N
        transpose.setText("TRANSPOSE");
        transpose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transposeActionPerformed(evt);
            }
        });
        getContentPane().add(transpose, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 380, 110, -1));

        bG_matrix2x2.add(sum);
        sum.setFont(new java.awt.Font("Tekton Pro", 0, 14)); // NOI18N
        sum.setText("SUM");
        sum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sumActionPerformed(evt);
            }
        });
        getContentPane().add(sum, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 350, 60, 23));

        matres.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        matres.setText("RESULT");
        getContentPane().add(matres, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 320, 70, 20));

        matB.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        matB.setText("MATRIX B");
        getContentPane().add(matB, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 120, 90, 20));

        B11.setBackground(new java.awt.Color(153, 204, 255));
        B11.setFont(new java.awt.Font("Cambria Math", 0, 24)); // NOI18N
        B11.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        B11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 153, 255)));
        getContentPane().add(B11, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 150, 50, 40));

        B12.setBackground(new java.awt.Color(153, 204, 255));
        B12.setFont(new java.awt.Font("Cambria Math", 0, 24)); // NOI18N
        B12.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        B12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 153, 255)));
        getContentPane().add(B12, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 150, 50, 40));

        B22.setBackground(new java.awt.Color(153, 204, 255));
        B22.setFont(new java.awt.Font("Cambria Math", 0, 24)); // NOI18N
        B22.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        B22.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 153, 255)));
        getContentPane().add(B22, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 210, 50, 40));

        B21.setBackground(new java.awt.Color(153, 204, 255));
        B21.setFont(new java.awt.Font("Cambria Math", 0, 24)); // NOI18N
        B21.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        B21.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 153, 255)));
        getContentPane().add(B21, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 210, 50, 40));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Kalkulator/kurung siku.png"))); // NOI18N
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 130, -1, 140));

        matA.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        matA.setText("MATRIX A");
        getContentPane().add(matA, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 120, 90, 20));

        A12.setBackground(new java.awt.Color(153, 204, 255));
        A12.setFont(new java.awt.Font("Cambria Math", 0, 24)); // NOI18N
        A12.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        A12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 153, 255)));
        getContentPane().add(A12, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 150, 50, 40));

        A11.setBackground(new java.awt.Color(153, 204, 255));
        A11.setFont(new java.awt.Font("Cambria Math", 0, 24)); // NOI18N
        A11.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        A11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 153, 255)));
        getContentPane().add(A11, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 150, 50, 40));

        A22.setBackground(new java.awt.Color(153, 204, 255));
        A22.setFont(new java.awt.Font("Cambria Math", 0, 24)); // NOI18N
        A22.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        A22.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 153, 255)));
        getContentPane().add(A22, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 210, 50, 40));

        A21.setBackground(new java.awt.Color(153, 204, 255));
        A21.setFont(new java.awt.Font("Cambria Math", 0, 24)); // NOI18N
        A21.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        A21.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 153, 255)));
        getContentPane().add(A21, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 210, 50, 40));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Kalkulator/kurung siku.png"))); // NOI18N
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, -1, 140));

        jB_back.setBackground(new java.awt.Color(53, 80, 177));
        jB_back.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jB_back.setText("BACK");
        jB_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_backActionPerformed(evt);
            }
        });
        getContentPane().add(jB_back, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 500, -1, 31));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Kalkulator/calculator logo.png"))); // NOI18N
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jB_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_backActionPerformed
        new MultiCal_Home().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jB_backActionPerformed

    private void jB_calculateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_calculateActionPerformed
        int matrixA[][] = new int[2][2];
        matrixA[0][0] = Integer.parseInt(A11.getText());
        matrixA[0][1] = Integer.parseInt(A12.getText());
        matrixA[1][0] = Integer.parseInt(A21.getText());
        matrixA[1][1] = Integer.parseInt(A22.getText());

        int matrixB[][] = new int[2][2];
        matrixB[0][0] = Integer.parseInt(B11.getText());
        matrixB[0][1] = Integer.parseInt(B12.getText());
        matrixB[1][0] = Integer.parseInt(B21.getText());
        matrixB[1][1] = Integer.parseInt(B22.getText());

        int matrixC[][] = new int[2][2];

        if (sum.isSelected()) {
            for (int i = 0; i < matrixA.length; i++) {
                for (int j = 0; j < matrixA[0].length; j++) {
                    matrixC[i][j] = matrixA[i][j] + matrixB[i][j];
                }
            }
        } else if (subtract.isSelected()) {
            for (int i = 0; i < matrixA.length; i++) {
                for (int j = 0; j < matrixA[0].length; j++) {
                    matrixC[i][j] = matrixA[i][j] - matrixB[i][j];
                }
            }
        } else if (multiply.isSelected()) {
            matrixC[0][0] = (matrixA[0][0] * matrixB[0][0]) + (matrixA[0][1] * matrixB[1][0]);
            matrixC[0][1] = (matrixA[0][0] * matrixB[0][1]) + (matrixA[0][1] * matrixB[1][1]);
            matrixC[1][0] = (matrixA[1][0] * matrixB[0][0]) + (matrixA[1][1] * matrixB[1][0]);
            matrixC[1][1] = (matrixA[1][0] * matrixB[0][1]) + (matrixA[1][1] * matrixB[1][1]);
        } else if (determinan.isSelected()) {
            float det;
            det = (matrixA[0][0] * matrixA[1][1]) - (matrixA[1][0] * matrixA[0][1]);
            singleres.setText(String.valueOf(det));
        } else if (transpose.isSelected()) {
            for (int i = 0; i < matrixA.length; i++) {
                for (int j = 0; j < matrixA[0].length; j++) {
                    matrixC[j][i] = matrixA[i][j];
                }
            }
        }
        C11.setText(String.valueOf(matrixC[0][0]));
        C12.setText(String.valueOf(matrixC[0][1]));
        C21.setText(String.valueOf(matrixC[1][0]));
        C22.setText(String.valueOf(matrixC[1][1]));
    }//GEN-LAST:event_jB_calculateActionPerformed

    private void transposeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transposeActionPerformed
        B11.setEnabled(false);
        B12.setEnabled(false);
        B21.setEnabled(false);
        B22.setEnabled(false);

        kurung.setVisible(true);
        C11.setVisible(true);
        C12.setVisible(true);
        C21.setVisible(true);
        C22.setVisible(true);
        singleres.setVisible(false);
    }//GEN-LAST:event_transposeActionPerformed

    private void sumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sumActionPerformed
        B11.setEnabled(true);
        B12.setEnabled(true);
        B21.setEnabled(true);
        B22.setEnabled(true);

        kurung.setVisible(true);
        C11.setVisible(true);
        C12.setVisible(true);
        C21.setVisible(true);
        C22.setVisible(true);
        singleres.setVisible(false);
    }//GEN-LAST:event_sumActionPerformed

    private void subtractActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subtractActionPerformed
        B11.setEnabled(true);
        B12.setEnabled(true);
        B21.setEnabled(true);
        B22.setEnabled(true);

        kurung.setVisible(true);
        C11.setVisible(true);
        C12.setVisible(true);
        C21.setVisible(true);
        C22.setVisible(true);
        singleres.setVisible(false);
    }//GEN-LAST:event_subtractActionPerformed

    private void multiplyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_multiplyActionPerformed
        B11.setEnabled(true);
        B12.setEnabled(true);
        B21.setEnabled(true);
        B22.setEnabled(true);

        kurung.setVisible(true);
        C11.setVisible(true);
        C12.setVisible(true);
        C21.setVisible(true);
        C22.setVisible(true);
        singleres.setVisible(false);
    }//GEN-LAST:event_multiplyActionPerformed

    private void determinanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_determinanActionPerformed
        B11.setEnabled(false);
        B12.setEnabled(false);
        B21.setEnabled(false);
        B22.setEnabled(false);

        kurung.setVisible(false);
        C11.setVisible(false);
        C12.setVisible(false);
        C21.setVisible(false);
        C22.setVisible(false);
        singleres.setVisible(true);
        singleres.setText("");
    }//GEN-LAST:event_determinanActionPerformed

    private void jB_clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_clearActionPerformed
        A11.setText("");
        A12.setText("");
        A21.setText("");
        A22.setText("");
        B11.setText("");
        B12.setText("");
        B21.setText("");
        B22.setText("");
        C11.setText("");
        C12.setText("");
        C21.setText("");
        C22.setText("");
        singleres.setText("");
    }//GEN-LAST:event_jB_clearActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MultiCal_2x2MatrixCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MultiCal_2x2MatrixCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MultiCal_2x2MatrixCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MultiCal_2x2MatrixCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MultiCal_2x2MatrixCalculator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField A11;
    private javax.swing.JTextField A12;
    private javax.swing.JTextField A21;
    private javax.swing.JTextField A22;
    private javax.swing.JTextField B11;
    private javax.swing.JTextField B12;
    private javax.swing.JTextField B21;
    private javax.swing.JTextField B22;
    private javax.swing.JLabel C11;
    private javax.swing.JLabel C12;
    private javax.swing.JLabel C21;
    private javax.swing.JLabel C22;
    private javax.swing.ButtonGroup bG_matrix2x2;
    private javax.swing.JRadioButton determinan;
    private javax.swing.JButton jB_back;
    private javax.swing.JButton jB_calculate;
    private javax.swing.JButton jB_clear;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel kurung;
    private javax.swing.JLabel matA;
    private javax.swing.JLabel matB;
    private javax.swing.JLabel matres;
    private javax.swing.JRadioButton multiply;
    private javax.swing.JLabel singleres;
    private javax.swing.JRadioButton subtract;
    private javax.swing.JRadioButton sum;
    private javax.swing.JRadioButton transpose;
    // End of variables declaration//GEN-END:variables
}
