/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Kalkulator;

import javax.swing.ImageIcon;

/**
 *
 * @author USER
 */
public class MultiCal_NumberSystemConverter extends javax.swing.JFrame {
    int convert;
    String cal, a;
    /**
     * Creates new form MultiCal_SystemNumberConverter
     */
    public MultiCal_NumberSystemConverter() {
        initComponents();
        this.setTitle("MultiCal - System Number Converter");
        this.setLocationRelativeTo(this);
        ImageIcon icon = new ImageIcon("src/UAS_1955201016_MULTICAL/calculator logo.png");
        setIconImage(icon.getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel17 = new javax.swing.JLabel();
        jB_convert = new javax.swing.JButton();
        jB_clear = new javax.swing.JButton();
        jL_input = new javax.swing.JLabel();
        jT_input = new javax.swing.JTextField();
        jL_output = new javax.swing.JLabel();
        jT_output = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jC_from = new javax.swing.JComboBox<>();
        jC_to = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jB_back = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel17.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(51, 51, 255));
        jLabel17.setText("What's your choice?");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 90, 250, 40));

        jB_convert.setBackground(new java.awt.Color(101, 134, 177));
        jB_convert.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jB_convert.setText("CONVERT");
        jB_convert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_convertActionPerformed(evt);
            }
        });
        getContentPane().add(jB_convert, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 290, 110, 40));

        jB_clear.setBackground(new java.awt.Color(101, 134, 177));
        jB_clear.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jB_clear.setText("CLEAR");
        jB_clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_clearActionPerformed(evt);
            }
        });
        getContentPane().add(jB_clear, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 380, 110, 40));

        jL_input.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jL_input.setText("INPUT");
        getContentPane().add(jL_input, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, 60, 20));

        jT_input.setBackground(new java.awt.Color(153, 204, 255));
        jT_input.setFont(new java.awt.Font("Cambria Math", 0, 24)); // NOI18N
        jT_input.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jT_input.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 153, 255)));
        getContentPane().add(jT_input, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 290, 290, 40));

        jL_output.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jL_output.setText("OUTPUT");
        getContentPane().add(jL_output, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 350, 70, 20));

        jT_output.setBackground(new java.awt.Color(153, 204, 255));
        jT_output.setFont(new java.awt.Font("Cambria Math", 0, 24)); // NOI18N
        jT_output.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jT_output.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 153, 255)));
        getContentPane().add(jT_output, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 380, 290, 40));

        jLabel10.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel10.setText("FROM");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, 60, 20));

        jC_from.setBackground(new java.awt.Color(102, 102, 255));
        jC_from.setFont(new java.awt.Font("Cambria Math", 0, 14)); // NOI18N
        jC_from.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- PILIH", "BINER", "OKTAL", "DESIMAL", "HEKSADESIMAL" }));
        getContentPane().add(jC_from, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, 150, 30));

        jC_to.setBackground(new java.awt.Color(102, 102, 255));
        jC_to.setFont(new java.awt.Font("Cambria Math", 0, 14)); // NOI18N
        jC_to.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- PILIH", "BINER", "OKTAL", "DESIMAL", "HEKSADESIMAL" }));
        getContentPane().add(jC_to, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 180, 150, 30));

        jLabel4.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel4.setText("TO");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 150, 60, 20));

        jB_back.setBackground(new java.awt.Color(53, 80, 177));
        jB_back.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jB_back.setText("BACK");
        jB_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_backActionPerformed(evt);
            }
        });
        getContentPane().add(jB_back, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 500, -1, 31));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Kalkulator/calculator logo.png"))); // NOI18N
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jB_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_backActionPerformed
        new MultiCal_Home().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jB_backActionPerformed

    private void jB_convertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_convertActionPerformed
        if(jC_from.getSelectedItem().equals("BINER")){
            if(jC_to.getSelectedItem().equals("BINER")){
                a = jT_input.getText();
                cal = a;
            }
            else if(jC_to.getSelectedItem().equals("OKTAL")){
                convert = Integer.parseInt(jT_input.getText(), 2);
                cal = Integer.toOctalString(convert);
            }
            else if(jC_to.getSelectedItem().equals("DESIMAL")){
                convert = Integer.parseInt(jT_input.getText(), 2);
                cal = String.format("%d", convert);
            }
            else if(jC_to.getSelectedItem().equals("HEKSADESIMAL")){
                convert = Integer.parseInt(jT_input.getText(), 2);
                cal = Integer.toHexString(convert);
            }
        }
        else if(jC_from.getSelectedItem().equals("OKTAL")){
            if(jC_to.getSelectedItem().equals("BINER")){
                convert = Integer.parseInt(jT_input.getText(), 8);
                cal = Integer.toBinaryString(convert);
            }
            else if(jC_to.getSelectedItem().equals("OKTAL")){
                a = jT_input.getText();
                cal = a;
            }
            else if(jC_to.getSelectedItem().equals("DESIMAL")){
                convert = Integer.parseInt(jT_input.getText(), 8);
                cal = String.format("%d", convert);
            }
            else if(jC_to.getSelectedItem().equals("HEKSADESIMAL")){
                convert = Integer.parseInt(jT_input.getText(), 8);
                cal = Integer.toHexString(convert);
            }
        }
        else if(jC_from.getSelectedItem().equals("DESIMAL")){
            if(jC_to.getSelectedItem().equals("BINER")){
                convert = Integer.parseInt(jT_input.getText());
                cal = Integer.toBinaryString(convert);
            }
            else if(jC_to.getSelectedItem().equals("OKTAL")){
                convert = Integer.parseInt(jT_input.getText());
                cal = Integer.toOctalString(convert);
            }
            else if(jC_to.getSelectedItem().equals("DESIMAL")){
                a = jT_input.getText();
                cal = a;
            }
            else if(jC_to.getSelectedItem().equals("HEKSADESIMAL")){
                convert = Integer.parseInt(jT_input.getText());
                cal = Integer.toHexString(convert);
            }
        }
        else if(jC_from.getSelectedItem().equals("HEKSADESIMAL")){
            if(jC_to.getSelectedItem().equals("BINER")){
                convert = Integer.parseInt(jT_input.getText(), 16);
                cal = Integer.toBinaryString(convert);
            }
            else if(jC_to.getSelectedItem().equals("OKTAL")){
                convert = Integer.parseInt(jT_input.getText(), 16);
                cal = Integer.toOctalString(convert);
            }
            else if(jC_to.getSelectedItem().equals("DESIMAL")){
                convert = Integer.parseInt(jT_input.getText(), 16);
                cal = Integer.toString(convert);
            }
            else if(jC_to.getSelectedItem().equals("HEKSADESIMAL")){
                a = jT_input.getText();
                cal = a;
            }
        }
        jT_output.setText(cal +  " ");
    }//GEN-LAST:event_jB_convertActionPerformed

    private void jB_clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_clearActionPerformed
        jT_input.setText("");
        jT_output.setText("");
        jC_from.setSelectedItem("-- PILIH");
        jC_to.setSelectedItem("-- PILIH");
    }//GEN-LAST:event_jB_clearActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MultiCal_NumberSystemConverter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MultiCal_NumberSystemConverter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MultiCal_NumberSystemConverter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MultiCal_NumberSystemConverter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MultiCal_NumberSystemConverter().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jB_back;
    private javax.swing.JButton jB_clear;
    private javax.swing.JButton jB_convert;
    private javax.swing.JComboBox<String> jC_from;
    private javax.swing.JComboBox<String> jC_to;
    private javax.swing.JLabel jL_input;
    private javax.swing.JLabel jL_output;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jT_input;
    private javax.swing.JTextField jT_output;
    // End of variables declaration//GEN-END:variables
}
