/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Kalkulator;

import javax.swing.ImageIcon;

/**
 *
 * @author USER
 */
public class MultiCal_BasicCalculator extends javax.swing.JFrame {

    String bil;
    double cal, bil1, bil2;
    int select;

    /**
     * Creates new form MultiCal_BasicCalculator
     */
    public MultiCal_BasicCalculator() {
        initComponents();
        this.setTitle("MultiCal - Basic Calculator");
        this.setLocationRelativeTo(this);
        ImageIcon icon = new ImageIcon("src/UAS_1955201016_MULTICAL/calculator logo.png");
        setIconImage(icon.getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jB_exp = new javax.swing.JButton();
        jB_faktorial = new javax.swing.JButton();
        jB_cos = new javax.swing.JButton();
        jB_sin = new javax.swing.JButton();
        jB_tan = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jB_back = new javax.swing.JButton();
        jT_IO = new javax.swing.JTextField();
        jB_clear = new javax.swing.JButton();
        jB_7 = new javax.swing.JButton();
        jB_5 = new javax.swing.JButton();
        jB_6 = new javax.swing.JButton();
        jB_kali = new javax.swing.JButton();
        jB_8 = new javax.swing.JButton();
        jB_9 = new javax.swing.JButton();
        jB_bagi = new javax.swing.JButton();
        jB_4 = new javax.swing.JButton();
        jB_pangkat = new javax.swing.JButton();
        jB_akar = new javax.swing.JButton();
        jB_0 = new javax.swing.JButton();
        jB_1 = new javax.swing.JButton();
        jB_2 = new javax.swing.JButton();
        jB_3 = new javax.swing.JButton();
        jB_kurang = new javax.swing.JButton();
        jB_equals = new javax.swing.JButton();
        jB_koma = new javax.swing.JButton();
        jB_jumlah = new javax.swing.JButton();
        jB_plusmin = new javax.swing.JButton();
        jB_ln = new javax.swing.JButton();
        jB_mod = new javax.swing.JButton();
        jB_log = new javax.swing.JButton();
        jB_delete = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jB_exp.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jB_exp.setForeground(new java.awt.Color(255, 255, 255));
        jB_exp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Kalkulator/Button_exp.jpg"))); // NOI18N
        jB_exp.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Kalkulator/Rollover_exp.jpg"))); // NOI18N
        jB_exp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_expActionPerformed(evt);
            }
        });
        getContentPane().add(jB_exp, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 300, 60, 51));

        jB_faktorial.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jB_faktorial.setForeground(new java.awt.Color(255, 255, 255));
        jB_faktorial.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Kalkulator/Button_faktorial.jpg"))); // NOI18N
        jB_faktorial.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Kalkulator/Rollover_faktorial.jpg"))); // NOI18N
        jB_faktorial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_faktorialActionPerformed(evt);
            }
        });
        getContentPane().add(jB_faktorial, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 180, 60, 51));

        jB_cos.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jB_cos.setForeground(new java.awt.Color(255, 255, 255));
        jB_cos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Kalkulator/Button_cos.jpg"))); // NOI18N
        jB_cos.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Kalkulator/Rollover_cos.jpg"))); // NOI18N
        jB_cos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_cosActionPerformed(evt);
            }
        });
        getContentPane().add(jB_cos, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 360, 60, 51));

        jB_sin.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jB_sin.setForeground(new java.awt.Color(255, 255, 255));
        jB_sin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Kalkulator/Button_sin.jpg"))); // NOI18N
        jB_sin.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Kalkulator/Rollover_sin.jpg"))); // NOI18N
        jB_sin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_sinActionPerformed(evt);
            }
        });
        getContentPane().add(jB_sin, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 300, 60, 51));

        jB_tan.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jB_tan.setForeground(new java.awt.Color(255, 255, 255));
        jB_tan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Kalkulator/Button_tan.jpg"))); // NOI18N
        jB_tan.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Kalkulator/Rollover_tan.jpg"))); // NOI18N
        jB_tan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_tanActionPerformed(evt);
            }
        });
        getContentPane().add(jB_tan, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 420, 60, 51));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Kalkulator/calculator logo.png"))); // NOI18N
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jB_back.setBackground(new java.awt.Color(53, 80, 177));
        jB_back.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jB_back.setText("BACK");
        jB_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_backActionPerformed(evt);
            }
        });
        getContentPane().add(jB_back, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 500, -1, 30));

        jT_IO.setBackground(new java.awt.Color(102, 102, 102));
        jT_IO.setFont(new java.awt.Font("Comic Sans MS", 1, 36)); // NOI18N
        jT_IO.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jT_IO, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, 410, 67));

        jB_clear.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jB_clear.setForeground(new java.awt.Color(255, 255, 255));
        jB_clear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Kalkulator/Button_Clear.jpg"))); // NOI18N
        jB_clear.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Kalkulator/Rollover_Clear.jpg"))); // NOI18N
        jB_clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_clearActionPerformed(evt);
            }
        });
        getContentPane().add(jB_clear, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, 60, 51));

        jB_7.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jB_7.setForeground(new java.awt.Color(255, 255, 255));
        jB_7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Kalkulator/Button_7.jpg"))); // NOI18N
        jB_7.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Kalkulator/Rollover_7.jpg"))); // NOI18N
        jB_7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_7ActionPerformed(evt);
            }
        });
        getContentPane().add(jB_7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, 60, 51));

        jB_5.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jB_5.setForeground(new java.awt.Color(255, 255, 255));
        jB_5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Kalkulator/Button_5.jpg"))); // NOI18N
        jB_5.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Kalkulator/Rollover_5.jpg"))); // NOI18N
        jB_5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_5ActionPerformed(evt);
            }
        });
        getContentPane().add(jB_5, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 300, 60, 51));

        jB_6.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jB_6.setForeground(new java.awt.Color(255, 255, 255));
        jB_6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Kalkulator/Button_6.jpg"))); // NOI18N
        jB_6.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Kalkulator/Rollover_6.jpg"))); // NOI18N
        jB_6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_6ActionPerformed(evt);
            }
        });
        getContentPane().add(jB_6, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 300, 60, 51));

        jB_kali.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jB_kali.setForeground(new java.awt.Color(255, 255, 255));
        jB_kali.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Kalkulator/Button_kali.jpg"))); // NOI18N
        jB_kali.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Kalkulator/Rollover_kali.jpg"))); // NOI18N
        jB_kali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_kaliActionPerformed(evt);
            }
        });
        getContentPane().add(jB_kali, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 300, 60, 51));

        jB_8.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jB_8.setForeground(new java.awt.Color(255, 255, 255));
        jB_8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Kalkulator/Button_8.jpg"))); // NOI18N
        jB_8.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Kalkulator/Rollover_8.jpg"))); // NOI18N
        jB_8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_8ActionPerformed(evt);
            }
        });
        getContentPane().add(jB_8, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 240, 60, 51));

        jB_9.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jB_9.setForeground(new java.awt.Color(255, 255, 255));
        jB_9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Kalkulator/Button_9.jpg"))); // NOI18N
        jB_9.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Kalkulator/Rollover_9.jpg"))); // NOI18N
        jB_9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_9ActionPerformed(evt);
            }
        });
        getContentPane().add(jB_9, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 240, 60, 51));

        jB_bagi.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jB_bagi.setForeground(new java.awt.Color(255, 255, 255));
        jB_bagi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Kalkulator/Button_bagi.jpg"))); // NOI18N
        jB_bagi.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Kalkulator/Rollover_bagi.jpg"))); // NOI18N
        jB_bagi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_bagiActionPerformed(evt);
            }
        });
        getContentPane().add(jB_bagi, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 240, 60, 51));

        jB_4.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jB_4.setForeground(new java.awt.Color(255, 255, 255));
        jB_4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Kalkulator/Button_4.jpg"))); // NOI18N
        jB_4.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Kalkulator/Rollover_4.jpg"))); // NOI18N
        jB_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_4ActionPerformed(evt);
            }
        });
        getContentPane().add(jB_4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, 60, 51));

        jB_pangkat.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jB_pangkat.setForeground(new java.awt.Color(255, 255, 255));
        jB_pangkat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Kalkulator/Button_Pangkat.jpg"))); // NOI18N
        jB_pangkat.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Kalkulator/Rollover_Pangkat.jpg"))); // NOI18N
        jB_pangkat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_pangkatActionPerformed(evt);
            }
        });
        getContentPane().add(jB_pangkat, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 360, 60, 51));

        jB_akar.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jB_akar.setForeground(new java.awt.Color(255, 255, 255));
        jB_akar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Kalkulator/Button_Akar.jpg"))); // NOI18N
        jB_akar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Kalkulator/Rollover_Akar.jpg"))); // NOI18N
        jB_akar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_akarActionPerformed(evt);
            }
        });
        getContentPane().add(jB_akar, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 420, 60, 51));

        jB_0.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jB_0.setForeground(new java.awt.Color(255, 255, 255));
        jB_0.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Kalkulator/Button_0.jpg"))); // NOI18N
        jB_0.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Kalkulator/Rollover_0.jpg"))); // NOI18N
        jB_0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_0ActionPerformed(evt);
            }
        });
        getContentPane().add(jB_0, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 420, 60, 51));

        jB_1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jB_1.setForeground(new java.awt.Color(255, 255, 255));
        jB_1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Kalkulator/Button_1.jpg"))); // NOI18N
        jB_1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Kalkulator/Rollover_1.jpg"))); // NOI18N
        jB_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_1ActionPerformed(evt);
            }
        });
        getContentPane().add(jB_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 360, 60, 51));

        jB_2.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jB_2.setForeground(new java.awt.Color(255, 255, 255));
        jB_2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Kalkulator/Button_2.jpg"))); // NOI18N
        jB_2.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Kalkulator/Rollover_2.jpg"))); // NOI18N
        jB_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_2ActionPerformed(evt);
            }
        });
        getContentPane().add(jB_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 360, 60, 51));

        jB_3.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jB_3.setForeground(new java.awt.Color(255, 255, 255));
        jB_3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Kalkulator/Button_3.jpg"))); // NOI18N
        jB_3.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Kalkulator/Rollover_3.jpg"))); // NOI18N
        jB_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_3ActionPerformed(evt);
            }
        });
        getContentPane().add(jB_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 360, 60, 51));

        jB_kurang.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jB_kurang.setForeground(new java.awt.Color(255, 255, 255));
        jB_kurang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Kalkulator/Button_kurang.jpg"))); // NOI18N
        jB_kurang.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Kalkulator/Rollover_kurang.jpg"))); // NOI18N
        jB_kurang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_kurangActionPerformed(evt);
            }
        });
        getContentPane().add(jB_kurang, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 360, 60, 51));

        jB_equals.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jB_equals.setForeground(new java.awt.Color(255, 255, 255));
        jB_equals.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Kalkulator/Button_equals.jpg"))); // NOI18N
        jB_equals.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Kalkulator/Rollover_equals.jpg"))); // NOI18N
        jB_equals.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_equalsActionPerformed(evt);
            }
        });
        getContentPane().add(jB_equals, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 420, 60, 51));

        jB_koma.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jB_koma.setForeground(new java.awt.Color(255, 255, 255));
        jB_koma.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Kalkulator/Button_koma.jpg"))); // NOI18N
        jB_koma.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Kalkulator/Rollover_koma.jpg"))); // NOI18N
        jB_koma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_komaActionPerformed(evt);
            }
        });
        getContentPane().add(jB_koma, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 420, 60, 51));

        jB_jumlah.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jB_jumlah.setForeground(new java.awt.Color(255, 255, 255));
        jB_jumlah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Kalkulator/Button_jumlah.jpg"))); // NOI18N
        jB_jumlah.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Kalkulator/Rollover_jumlah.jpg"))); // NOI18N
        jB_jumlah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_jumlahActionPerformed(evt);
            }
        });
        getContentPane().add(jB_jumlah, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 420, 60, 51));

        jB_plusmin.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jB_plusmin.setForeground(new java.awt.Color(255, 255, 255));
        jB_plusmin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Kalkulator/Button_+-.jpg"))); // NOI18N
        jB_plusmin.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Kalkulator/Rollover_+-.jpg"))); // NOI18N
        jB_plusmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_plusminActionPerformed(evt);
            }
        });
        getContentPane().add(jB_plusmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 180, 60, 51));

        jB_ln.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jB_ln.setForeground(new java.awt.Color(255, 255, 255));
        jB_ln.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Kalkulator/Button_ln.jpg"))); // NOI18N
        jB_ln.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Kalkulator/Rollover_ln.jpg"))); // NOI18N
        jB_ln.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_lnActionPerformed(evt);
            }
        });
        getContentPane().add(jB_ln, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 240, 60, 51));

        jB_mod.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jB_mod.setForeground(new java.awt.Color(255, 255, 255));
        jB_mod.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Kalkulator/Button_persen.jpg"))); // NOI18N
        jB_mod.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Kalkulator/Rollover_persen.jpg"))); // NOI18N
        jB_mod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_modActionPerformed(evt);
            }
        });
        getContentPane().add(jB_mod, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 180, 60, 51));

        jB_log.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jB_log.setForeground(new java.awt.Color(255, 255, 255));
        jB_log.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Kalkulator/Button_log.jpg"))); // NOI18N
        jB_log.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Kalkulator/Rollover_log.jpg"))); // NOI18N
        jB_log.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_logActionPerformed(evt);
            }
        });
        getContentPane().add(jB_log, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 240, 60, 51));

        jB_delete.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jB_delete.setForeground(new java.awt.Color(255, 255, 255));
        jB_delete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Kalkulator/Button_Delete.jpg"))); // NOI18N
        jB_delete.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Kalkulator/Rollover_Delete.jpg"))); // NOI18N
        jB_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_deleteActionPerformed(evt);
            }
        });
        getContentPane().add(jB_delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 180, 130, 51));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jB_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_backActionPerformed
        new MultiCal_Home().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jB_backActionPerformed

    private void jB_0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_0ActionPerformed
        bil = jT_IO.getText() + 0;
        jT_IO.setText(bil);
    }//GEN-LAST:event_jB_0ActionPerformed

    private void jB_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_1ActionPerformed
        bil = jT_IO.getText() + 1;
        jT_IO.setText(bil);
    }//GEN-LAST:event_jB_1ActionPerformed

    private void jB_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_2ActionPerformed
        bil = jT_IO.getText() + 2;
        jT_IO.setText(bil);
    }//GEN-LAST:event_jB_2ActionPerformed

    private void jB_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_3ActionPerformed
        bil = jT_IO.getText() + 3;
        jT_IO.setText(bil);
    }//GEN-LAST:event_jB_3ActionPerformed

    private void jB_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_4ActionPerformed
        bil = jT_IO.getText() + 4;
        jT_IO.setText(bil);
    }//GEN-LAST:event_jB_4ActionPerformed

    private void jB_5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_5ActionPerformed
        bil = jT_IO.getText() + 5;
        jT_IO.setText(bil);
    }//GEN-LAST:event_jB_5ActionPerformed

    private void jB_6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_6ActionPerformed
        bil = jT_IO.getText() + 6;
        jT_IO.setText(bil);
    }//GEN-LAST:event_jB_6ActionPerformed

    private void jB_7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_7ActionPerformed
        bil = jT_IO.getText() + 7;
        jT_IO.setText(bil);
    }//GEN-LAST:event_jB_7ActionPerformed

    private void jB_8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_8ActionPerformed
        bil = jT_IO.getText() + 8;
        jT_IO.setText(bil);
    }//GEN-LAST:event_jB_8ActionPerformed

    private void jB_9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_9ActionPerformed
        bil = jT_IO.getText() + 9;
        jT_IO.setText(bil);
    }//GEN-LAST:event_jB_9ActionPerformed

    private void jB_clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_clearActionPerformed
        jT_IO.setText("");
    }//GEN-LAST:event_jB_clearActionPerformed

    private void jB_jumlahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_jumlahActionPerformed
        bil = jT_IO.getText() + " + ";
        jT_IO.setText(bil);
        select = 1;
    }//GEN-LAST:event_jB_jumlahActionPerformed

    private void jB_kurangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_kurangActionPerformed
        bil = jT_IO.getText() + " - ";
        jT_IO.setText(bil);
        select = 1;
    }//GEN-LAST:event_jB_kurangActionPerformed

    private void jB_kaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_kaliActionPerformed
        bil = jT_IO.getText() + " × ";
        jT_IO.setText(bil);
        select = 1;
    }//GEN-LAST:event_jB_kaliActionPerformed

    private void jB_bagiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_bagiActionPerformed
        bil = jT_IO.getText() + " ÷ ";
        jT_IO.setText(bil);
        select = 1;
    }//GEN-LAST:event_jB_bagiActionPerformed

    private void jB_equalsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_equalsActionPerformed
        switch (select) {
            case 1:
                int x = jT_IO.getText().length();
                bil1 = Double.parseDouble(bil.substring(0, bil.indexOf(" ")));
                bil2 = Double.parseDouble(bil.substring(bil.indexOf(" ") + 2, x));
                String pilih1 = bil.substring(bil.indexOf(" ") + 1, bil.indexOf(" ") + 2);

                if (pilih1.equals("+")) {
                    cal = bil1 + bil2;
                } else if (pilih1.equals("-")) {
                    cal = bil1 - bil2;
                } else if (pilih1.equals("×")) {
                    cal = bil1 * bil2;
                } else if (pilih1.equals("÷")) {
                    cal = bil1 / bil2;
                } else if (pilih1.equals("%")) {
                    cal = bil1 % bil2;
                } else if (pilih1.equals("^")) {
                    cal = Math.pow(bil1, bil2);
                }
                break;
            case 2:
                int y = jT_IO.getText().length();
                bil2 = Double.parseDouble(bil.substring(bil.indexOf(" ") + 1, y));
                String pilih2 = bil.substring(0, bil.indexOf(" "));

                if (pilih2.equals("√")) {
                    cal = Math.sqrt(bil2);
                } else if (pilih2.equals("log")) {
                    cal = Math.log10(bil2);
                } else if (pilih2.equals("sin")) {
                    cal = Math.sin(Math.toRadians(bil2));
                } else if (pilih2.equals("cos")) {
                    cal = Math.cos(Math.toRadians(bil2));
                } else if (pilih2.equals("tan")) {
                    cal = Math.tan(Math.toRadians(bil2));
                } else if (pilih2.equals("ln")) {
                    cal = Math.log(bil2);
                } else if (pilih2.equals("exp")) {
                    cal = Math.exp(bil2);
                }
                break;
            case 3:
                bil1 = Double.parseDouble(bil.substring(0, bil.indexOf(" ")));
                String pilih3 = bil.substring(bil.indexOf(" ") + 1, bil.indexOf(" ") + 2);

                if (pilih3.equals("!")) {
                    cal = 1;
                    for (double i = bil1; i > 0; i--) {
                        cal *= i;
                    }
                }
                break;
        }
        jT_IO.setText(String.valueOf(cal));
    }//GEN-LAST:event_jB_equalsActionPerformed

    private void jB_komaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_komaActionPerformed
        bil = jT_IO.getText() + ".";
        jT_IO.setText(bil);
    }//GEN-LAST:event_jB_komaActionPerformed

    private void jB_pangkatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_pangkatActionPerformed
        bil = jT_IO.getText() + " ^ ";
        jT_IO.setText(bil);
        select = 1;
    }//GEN-LAST:event_jB_pangkatActionPerformed

    private void jB_akarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_akarActionPerformed
        bil = jT_IO.getText() + "√ ";
        jT_IO.setText(bil);
        select = 2;
    }//GEN-LAST:event_jB_akarActionPerformed

    private void jB_expActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_expActionPerformed
        bil = jT_IO.getText() + "exp ";
        jT_IO.setText(bil);
        select = 2;
    }//GEN-LAST:event_jB_expActionPerformed

    private void jB_plusminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_plusminActionPerformed
        Double x = Double.valueOf(jT_IO.getText());
        Double y = -1 * x;
        jT_IO.setText(String.valueOf(y));
    }//GEN-LAST:event_jB_plusminActionPerformed

    private void jB_lnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_lnActionPerformed
        bil = jT_IO.getText() + "ln ";
        jT_IO.setText(bil);
        select = 2;
    }//GEN-LAST:event_jB_lnActionPerformed

    private void jB_modActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_modActionPerformed
        bil = jT_IO.getText() + " % ";
        jT_IO.setText(bil);
        select = 1;
    }//GEN-LAST:event_jB_modActionPerformed

    private void jB_faktorialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_faktorialActionPerformed
        bil = jT_IO.getText() + " !";
        jT_IO.setText(bil);
        select = 3;
    }//GEN-LAST:event_jB_faktorialActionPerformed

    private void jB_logActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_logActionPerformed
        bil = jT_IO.getText() + "log ";
        jT_IO.setText(bil);
        select = 2;
    }//GEN-LAST:event_jB_logActionPerformed

    private void jB_sinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_sinActionPerformed
        bil = jT_IO.getText() + "sin ";
        jT_IO.setText(bil);
        select = 2;
    }//GEN-LAST:event_jB_sinActionPerformed

    private void jB_cosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_cosActionPerformed
        bil = jT_IO.getText() + "cos ";
        jT_IO.setText(bil);
        select = 2;
    }//GEN-LAST:event_jB_cosActionPerformed

    private void jB_tanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_tanActionPerformed
        bil = jT_IO.getText() + "tan ";
        jT_IO.setText(bil);
        select = 2;
    }//GEN-LAST:event_jB_tanActionPerformed

    private void jB_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_deleteActionPerformed
        jT_IO.setText(bil.substring(0, jT_IO.getText().length() - 1));
    }//GEN-LAST:event_jB_deleteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MultiCal_BasicCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MultiCal_BasicCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MultiCal_BasicCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MultiCal_BasicCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MultiCal_BasicCalculator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jB_0;
    private javax.swing.JButton jB_1;
    private javax.swing.JButton jB_2;
    private javax.swing.JButton jB_3;
    private javax.swing.JButton jB_4;
    private javax.swing.JButton jB_5;
    private javax.swing.JButton jB_6;
    private javax.swing.JButton jB_7;
    private javax.swing.JButton jB_8;
    private javax.swing.JButton jB_9;
    private javax.swing.JButton jB_akar;
    private javax.swing.JButton jB_back;
    private javax.swing.JButton jB_bagi;
    private javax.swing.JButton jB_clear;
    private javax.swing.JButton jB_cos;
    private javax.swing.JButton jB_delete;
    private javax.swing.JButton jB_equals;
    private javax.swing.JButton jB_exp;
    private javax.swing.JButton jB_faktorial;
    private javax.swing.JButton jB_jumlah;
    private javax.swing.JButton jB_kali;
    private javax.swing.JButton jB_koma;
    private javax.swing.JButton jB_kurang;
    private javax.swing.JButton jB_ln;
    private javax.swing.JButton jB_log;
    private javax.swing.JButton jB_mod;
    private javax.swing.JButton jB_pangkat;
    private javax.swing.JButton jB_plusmin;
    private javax.swing.JButton jB_sin;
    private javax.swing.JButton jB_tan;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jT_IO;
    // End of variables declaration//GEN-END:variables
}
